#!/usr/bin/python 
import random

# Initialize the board.
board = [' '] * 9

def printBoard(board):
  print ' ' + board[0] + ' | ' + board[1] + ' | ' + board[2]
  print '--- --- ---'
  print ' ' + board[3] + ' | ' + board[4] + ' | ' + board[5]
  print '--- --- ---'
  print ' ' + board[6] + ' | ' + board[7] + ' | ' + board[8]

def checkWinner(board, move):
  piece = board[move]
  row = move/3
  col = move%3

  # Check row
  if piece == board[row*3] and piece == board[row*3+1] and piece == board[row*3+2]:
    return True

  # Check column
  if piece == board[col] and piece == board[col+3] and piece == board[col+6]:
    return True

  # Check diagonals
  if move%2 == 0:
    if piece == board[0] and piece == board[4] and piece == board[8]:
      return True
    if piece == board[2] and piece == board[4] and piece == board[6]:
      return True

  return False


moveCount = 0

while True:
  printBoard(board)
  move = int(raw_input('move (1-9): ')) - 1
  if board[move] != ' ':
    print 'Not a valid move.'
    continue
  board[move] = 'X'

  if checkWinner(board, move):
    printBoard(board)
    print 'Humanity Wins!'
    break;
  moveCount += 1
  
  if moveCount == 9:
    break;

  botMove = random.randint(0,8) 
  while board[botMove] != ' ':
    botMove = random.randint(0,8) 
  board[botMove] = 'O'

  if checkWinner(board, botMove):
    printBoard(board)
    print 'The Machines Have Won!'
    break;
  moveCount += 1

if moveCount == 9:
  printBoard(board)
  print 'DRAW'
